#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=4

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
REPO_ROOT=$(cd "$SCRIPT_DIR/.." && pwd)
MOBILE_DIR="$REPO_ROOT/packages/mobile"
GITHUB_REPO="spoofer8/portable.dev"
EAS_CLI=(bunx eas-cli@24.7.0)

require_value() {
  local key="$1" label="$2"
  if [[ -z "${!key}" ]]; then
    warn "$label cannot be empty. Re-run the wizard when you have it."
    exit 1
  fi
}

set_environment_secret() {
  local environment="$1" name="$2" value="$3"
  printf '%s' "$value" | gh secret set "$name" --repo "$GITHUB_REPO" --env "$environment" >/dev/null
  WRITTEN_SECRET+=("$environment/$name")
  printf '  %s✓ set%s GitHub %s secret %s\n' "$GREEN" "$RESET" "$environment" "$name"
}

set_environment_var() {
  local environment="$1" name="$2" value="$3"
  gh variable set "$name" --repo "$GITHUB_REPO" --env "$environment" --body "$value" >/dev/null
  printf '  %s✓ set%s GitHub %s variable %s\n' "$GREEN" "$RESET" "$environment" "$name"
}

set_eas_var() {
  local environment="$1" name="$2" value="$3" visibility="$4"
  (
    cd "$MOBILE_DIR"
    EXPO_TOKEN="$EXPO_TOKEN" "${EAS_CLI[@]}" env:set "$environment" \
      --name "$name" \
      --value "$value" \
      --visibility "$visibility" \
      --scope project \
      --non-interactive >/dev/null
  )
  printf '  %s✓ set%s EAS %s variable %s\n' "$GREEN" "$RESET" "$environment" "$name"
}

set_eas_file() {
  local environment="$1" name="$2" file_path="$3"
  (
    cd "$MOBILE_DIR"
    EXPO_TOKEN="$EXPO_TOKEN" "${EAS_CLI[@]}" env:set "$environment" \
      --name "$name" \
      --value "$file_path" \
      --type file \
      --visibility sensitive \
      --scope project \
      --non-interactive >/dev/null
  )
  printf '  %s✓ set%s EAS %s file %s\n' "$GREEN" "$RESET" "$environment" "$name"
}

command -v gh >/dev/null 2>&1 || { printf 'gh is required\n' >&2; exit 1; }
gh auth status >/dev/null 2>&1 || { printf 'Run gh auth login first\n' >&2; exit 1; }
command -v sentry >/dev/null 2>&1 || { printf 'The Sentry CLI is required\n' >&2; exit 1; }
command -v jq >/dev/null 2>&1 || { printf 'jq is required\n' >&2; exit 1; }

banner "Portable mobile delivery setup"

stage "Read Sentry configuration"
say "The Sentry CLI supplies the project, DSN, and upload token without printing the token."
if ! sentry auth status >/dev/null 2>&1; then
  sentry auth login
fi
sentry_info=$(sentry info --json 2>/dev/null || true)
SENTRY_ORG=$(printf '%s' "$sentry_info" | jq -r '.config.org // empty')
SENTRY_PROJECT=$(printf '%s' "$sentry_info" | jq -r '.config.project // empty')

if [[ -z "$SENTRY_ORG" || -z "$SENTRY_PROJECT" ]]; then
  say "No default Sentry project is configured, so this wizard will create one."
  ask SENTRY_ORG "Sentry organization slug:"
  ask SENTRY_PROJECT_NAME "New project name [portable-mobile]:"
  SENTRY_PROJECT_NAME=${SENTRY_PROJECT_NAME:-portable-mobile}
  require_value SENTRY_ORG "Sentry organization slug"
  project_json=$(sentry project create "$SENTRY_ORG/$SENTRY_PROJECT_NAME:react-native" --json)
  SENTRY_PROJECT=$(printf '%s' "$project_json" | jq -er '.project.slug')
  EXPO_PUBLIC_SENTRY_DSN=$(printf '%s' "$project_json" | jq -er '.dsn')
  sentry cli defaults org "$SENTRY_ORG" --yes >/dev/null
  sentry cli defaults project "$SENTRY_PROJECT" --yes >/dev/null
else
  project_json=$(sentry project view "$SENTRY_ORG/$SENTRY_PROJECT" --json)
  EXPO_PUBLIC_SENTRY_DSN=$(printf '%s' "$project_json" | jq -er '.[0].dsn')
fi

SENTRY_AUTH_TOKEN=$(sentry auth token)
require_value SENTRY_AUTH_TOKEN "Sentry auth token"
printf '  %s✓ detected%s %s/%s and verified CLI authentication\n' \
  "$GREEN" "$RESET" "$SENTRY_ORG" "$SENTRY_PROJECT"

stage "Create the Expo access token"
say "This token lets GitHub Actions publish OTA updates and start EAS builds."
open_url "https://expo.dev/accounts/spo0fer/settings/access-tokens"
step "Create a personal access token named portable-mobile-github and copy it."
ask_secret EXPO_TOKEN "Expo access token:"
require_value EXPO_TOKEN "Expo access token"
if (cd "$MOBILE_DIR" && EXPO_TOKEN="$EXPO_TOKEN" "${EAS_CLI[@]}" whoami >/dev/null); then
  printf '  %s✓ verified%s Expo token access\n' "$GREEN" "$RESET"
else
  warn "Expo rejected the token. Re-run after creating a valid access token."
  exit 1
fi

stage "Store credentials"
say "Writing secrets to protected GitHub environments and EAS. Values stay hidden."
FIREBASE_PLIST_PATH="$MOBILE_DIR/GoogleService-Info.plist"
[[ -f "$FIREBASE_PLIST_PATH" ]] || {
  warn "Missing $FIREBASE_PLIST_PATH. Download it from the Firebase iOS app settings."
  exit 1
}
GOOGLE_SERVICE_INFO_PLIST_BASE64=$(base64 < "$FIREBASE_PLIST_PATH")

ENV_FILE="$MOBILE_DIR/.env"
write_env EXPO_PUBLIC_SENTRY_DSN "$EXPO_PUBLIC_SENTRY_DSN"
write_env EXPO_PUBLIC_ENABLE_SENTRY_TEST "true"
write_env EXPO_PUBLIC_SENTRY_ENVIRONMENT "development"

ENV_FILE="$MOBILE_DIR/.env.sentry-build-plugin"
write_env SENTRY_AUTH_TOKEN "$SENTRY_AUTH_TOKEN"
write_env SENTRY_ORG "$SENTRY_ORG"
write_env SENTRY_PROJECT "$SENTRY_PROJECT"
chmod 600 "$ENV_FILE"

for deployment_environment in preview production; do
  set_environment_secret "$deployment_environment" EXPO_TOKEN "$EXPO_TOKEN"
  set_environment_secret "$deployment_environment" SENTRY_AUTH_TOKEN "$SENTRY_AUTH_TOKEN"
  set_environment_secret "$deployment_environment" GOOGLE_SERVICE_INFO_PLIST_BASE64 "$GOOGLE_SERVICE_INFO_PLIST_BASE64"
  set_environment_var "$deployment_environment" SENTRY_ORG "$SENTRY_ORG"
  set_environment_var "$deployment_environment" SENTRY_PROJECT "$SENTRY_PROJECT"
  set_environment_var "$deployment_environment" EXPO_PUBLIC_SENTRY_DSN "$EXPO_PUBLIC_SENTRY_DSN"
  set_environment_var "$deployment_environment" EXPO_PUBLIC_SENTRY_ENVIRONMENT "$deployment_environment"

  set_eas_var "$deployment_environment" SENTRY_AUTH_TOKEN "$SENTRY_AUTH_TOKEN" secret
  set_eas_var "$deployment_environment" SENTRY_ORG "$SENTRY_ORG" plaintext
  set_eas_var "$deployment_environment" SENTRY_PROJECT "$SENTRY_PROJECT" plaintext
  set_eas_var "$deployment_environment" EXPO_PUBLIC_SENTRY_DSN "$EXPO_PUBLIC_SENTRY_DSN" plaintext
  set_eas_var "$deployment_environment" EXPO_PUBLIC_SENTRY_ENVIRONMENT "$deployment_environment" plaintext
  set_eas_file "$deployment_environment" GOOGLE_SERVICES_FILE "$FIREBASE_PLIST_PATH"
done

stage "Build the untethered preview"
say "The first build may ask you to sign in to Apple and confirm signing credentials."
if confirm "Start the first iOS preview build now?"; then
  (cd "$MOBILE_DIR" && EXPO_TOKEN="$EXPO_TOKEN" "${EAS_CLI[@]}" build --profile preview --platform ios)
else
  SKIPPED+=("Initial preview build (run: cd packages/mobile && bunx eas-cli@24.7.0 build --profile preview --platform ios)")
fi

finish
